---

- hosts: all
  become: true
  pre_tasks:

  - name: epel-release download
    yum:
      name:
        - epel-release
    when: ansible_distribution == "CentOS"

  - name: Update and Upgrade (CentOS Server)
    yum:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "CentOS"

  - name: Update and Upgrade (Ubuntu Sever)
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: Install Docker (Ubuntu)
    apt:
      name:
        - docker.io
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: Install Docker (CentOS)
    command: snap install docker --classic
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: Install Docker (Ubuntu)
    apt:
      name:
        - docker.io
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: Install Docker (CentOS)
    command: snap install docker --classic
    when: ansible_distribution == "CentOS"
